### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by lockys** [hsnl-dev/VoiceIn-Web-Service#4]
- [x] GET /api/v1/accounts/{user-uuid}
- [x] PUT /api/v1/accounts/{user-uuid}
- [x] DELETE /api/v1/accounts/{user-uuid}
- [x] POST /api/v1/accounts/{user-uuid}/calls
- [x] GET /api/v1/accounts/{user-uuid}/contacts
- [x] POST/api/v1/accounts/{user-uuid}/contacts
- [x] PUT /api/v1/accounts/{user-uuid}/contacts/{contact-id}
- [x] DELETE /api/v1/accounts/{user-uuid}/contacts/{contact-id}
- [x] POST  /api/v1/accounts/{user-uuid}/qrcode
- [x] GET  /api/v1/accounts/{user-uuid}/qrcode
