### ISSUE TITLE
TODO List - 2

### ISSUE THREAD

**Issue by qoojung** [hsnl-dev/VoiceIn-Web-Service#5]
- [x] POST /api/v1/accounts/validations
- [x] POST /api/v1/accounts/tokens
- [x] DELETE /api/v1/accounts/tokens/{token}
- [x] POST  /api/v1/accounts/{user-uuid}/avatar
- [x] GET /api/v1/accounts/{user-uuid}/avatar?size={size}
- [x] POST /api/v1/icons/
- [x] POST /api/v1/icons/{relation-id}/calls
- [x] PUT /api/v1/icons/{icon-id}
- [x] GET /api/v1/providers/{provider-uuid}
